#' Data generation: time-event data from pgw distribution with censoring
#'
#'
#' Simulates time-event data with cencoring from a specified pgW distribution.
#' The data simulation works as follows:
#' The n time observations are generated by the \code{rpgw} function. All time observations
#' that lie behind the specified censoring time \code{ct} are substituted by the censoring
#' time itself. The censoring status is defined in a binary vector of length n. To each
#' observation with time point \eqn{t \leq} \code{ct}, status 1 (event observed) is assigned.
#' To each observation with time point \eqn{t \geq} \code{ct}, status 0 (no event observed)
#' is assigned.
#'
#' @param genpar A vector containing five elements, namely:
#' \enumerate{
#'       \item the sample size n,
#'       \item the censoring time ct
#'       \item the scale parameter of the pgw distribution,
#'       \item the shape parameter of the pgw distribution,
#'       \item the powershape parameter of the pgw distribution
#'        }
#'
#' @return A simulated time-event data frame of size n.
#' @export
#'



datagenpgw = function(genpar){
  N = genpar[1] # sample size
  ct = genpar[2] # censoring time
  scale = genpar[3] # scale parameter of pgW distribution
  shape = genpar[4] # shape parameter of pgW distribution
  powershape = genpar[5] # powershape parameter of pgW distribution


  samplecomplete = rpgw(N, scale = scale, shape = shape, powershape = powershape)

  samplecensored = samplecomplete

  samplecensored[which(samplecomplete > ct)] = ct
  status = rep(1, N)
  status[which(samplecomplete > ct)] = 0

  samplecensored = data.frame(time = samplecensored, status = status)
  return(samplecensored)
}




