#' Data generation: exponential and normal distributed event-times
#'
#' Simulation of data (same as for non-Bayesian approach)
#'
#' @details Input is a vector with 5 elements
#' \enumerate{
#' \item sample size n
#' \item backround rate br (= observed in the population)
#' \item Adverse drug reaction rate as prop. of the backround rate
#' \item rel. sd of the ADR generating process (relative means, the absolut sd = rel.sd*censor)
#' \item censor (= time point at which the cohort observation period ends)
#' }
#'
#' After prespecification of the input, the data simulation works as follows:
#'
#' The absolut number of cases due to backround causes (other than the adr) is
#' generated by the binomial distribution with \code{prob = br}.
#' The absolut number of cases due to the medication is generated by the
#' binomial distribution with \code{prob = br*adr}. All in all, the expected
#' number of events/cases within the dataset is
#' \eqn{n \cdot br (1 + adr)}.
#'
#' The event-times can have values between zero and censor. Time point zero is the date of
#' the medication (or start of regular medication) and the censor is the
#' official end time of the cohort study.
#'
#' For the br cases, the event-times are generated by an exponential distribution on
#' the interval [0, censor]. For the adr cases, event-times follow a normal
#' distribution. The mean of the normal distribution is chosen randomly within
#' the interval [0,censor]. The standard deviation is defined as
#' \eqn{ rel.sd \cdot censor}. All generated event-times
#' \eqn{\leq 0} are set to 1.
#'
#' @param genpar A vector containing five elements, namely:
#' \enumerate{
#'       \item the sample size n,
#'       \item the backround rate br,
#'       \item the ADR rate adr,
#'       \item the relative standard deviation of the ADR generating process rel.sd,
#'       \item the censor.
#'        See details for more information.
#'        }
#'
#' @return A simulated time-event data frame of size n.
#' @export
#'
#'
#'



datagenExpBr <- function(genpar){
  n = genpar[1]
  br = genpar[2]
  adr = genpar[3]
  rel.sd = genpar[4]
  censor = genpar[5]
  # Number of br & adr cases in the study
  n.br = rbinom(1,n, prob = br)

  n.adr = n*adr*br#rbinom(1,n, prob = br*adr)
  # event time for backround event candidates
  #t.br = runif(n.br, min = 0, max = censor)
  t.br=rexp(n-n.adr,-log(1-br)/censor)
  status<-c(rep(1,n))
  t.br[t.br>censor]<-censor
  status[which(t.br==censor)]<-0
  #print(which(t.br==censor))
  # mean timepoint for adr events
  m.adr = runif(1,0,censor)
  sd.adr = rel.sd*censor
  # event time for adr event candidates
  t.adr = rnorm(n.adr, mean = m.adr, sd = sd.adr)
  #print(c(m.adr,sd.adr))
  # adjustment for negativ timepoints
  if(sum(t.adr<=0)>0){
    t.adr[t.adr<=0] = 1
  }
  # number of events in the observation period
  #n.events = length(c(t.br, t.adr))
  # status vector for whole sample
  #status = c(rep(1,n.events))#, rep(0, n-n.events))
  # time vector (continuous values) for whole sample
  time = c(t.br, t.adr)#, rep(censor,n-n.events))
  print(length(time))
  # time vector (daily scale) for whole sample
  time = ceiling(time)
  dat = data.frame(time, status)
  # print(c(length(t.br), length(t.adr),table(status)))
  return(dat)
}



